package com.bacchoterra.financetracker.model;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity(tableName = "stock_table")
public class Stock  implements Serializable {

    private String stockName; //mandatory
    private long initialTimestamp; //mandatory
    private float averagePrice; //mandatory //mandatory after finished...null until finished
    private int quantity; //mandatory
    private float totalSpent; //mandatory (auto generate after initialPrice and quantity)

    private String expectedTimeInvested; //optional
    private String techniqueUsed; //optional
    private String corretora; //optional

    private long finalTimestamp; //mandatory after finished...null until finished
    private float finalPrice; //mandatory after finished...null until finished
    private float profit; // mandatory (autogenerated after isFinished becomes true)... null until finished

    private boolean isFinished; //false by default

    @PrimaryKey(autoGenerate = true)
    private int id;

    public Stock(String stockName, long initialTimestamp, long finalTimestamp, float averagePrice, int quantity, float totalSpent, int id, String expectedTimeInvested, boolean isFinished, float profit, String techniqueUsed) {
        this.stockName = stockName;
        this.initialTimestamp = initialTimestamp;
        this.finalTimestamp = finalTimestamp;
        this.averagePrice = averagePrice;
        this.quantity = quantity;
        this.totalSpent = totalSpent;
        this.id = id;
        this.expectedTimeInvested = expectedTimeInvested;
        this.isFinished = isFinished;
        this.profit = profit;
        this.techniqueUsed = techniqueUsed;
    }

    public Stock() {

        techniqueUsed = "";
        expectedTimeInvested = "";

        finalTimestamp = 0;
        profit = 0;

        isFinished = false;

    }

    public String getStockName() {
        return stockName;
    }

    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public long getInitialTimestamp() {
        return initialTimestamp;
    }

    public void setInitialTimestamp(long initialTimestamp) {
        this.initialTimestamp = initialTimestamp;
    }

    public float getFinalPrice() {
        return finalPrice;
    }

    public void setFinalPrice(float finalPrice) {
        this.finalPrice = finalPrice;
    }

    public long getFinalTimestamp() {
        return finalTimestamp;
    }

    public void setFinalTimestamp(long finalTimestamp) {
        this.finalTimestamp = finalTimestamp;
    }

    public float getAveragePrice() {
        return averagePrice;
    }

    public void setAveragePrice(float averagePrice) {
        this.averagePrice = averagePrice;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public float getTotalSpent() {
        return totalSpent;
    }

    public void setTotalSpent(float totalSpent) {
        this.totalSpent = totalSpent;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getExpectedTimeInvested() {
        return expectedTimeInvested;
    }

    public void setExpectedTimeInvested(String expectedTimeInvested) {
        this.expectedTimeInvested = expectedTimeInvested;
    }

    public boolean isFinished() {
        return isFinished;
    }

    public void setFinished(boolean finished) {
        isFinished = finished;
    }

    public float getProfit() {
        return profit;
    }

    public void setProfit(float profit) {
        this.profit = profit;
    }

    public String getTechniqueUsed() {
        return techniqueUsed;
    }

    public void setTechniqueUsed(String techniqueUsed) {
        this.techniqueUsed = techniqueUsed;
    }

    public String getCorretora() {
        return corretora;
    }

    public void setCorretora(String corretora) {
        this.corretora = corretora;
    }
}
